# This workflow will build a Java project with Maven
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: Java CI with Maven

on: [push, pull_request]

jobs:
  properties:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        java: [ 17 ]

    name: Java ${{ matrix.java }} compile

    steps:
      - uses: actions/checkout@v1
      - name: Setup java ${{ matrix.java }}
        uses: actions/setup-java@v1
        with:
          java-version: ${{ matrix.java }}
      - run: mvn clean verify